[baldr_pupils]
pupil1 = [ 1, 2, 3,]
pupil2 = [ 4, 5, 6,]

[beam2]
I2A = [ [ 1.1, 2.2,], [ 3.3, 4.4,],]

[beam2.pupil_mask]
mask = [ [ true, false,], [ false, true,],]
exterior = [ [ false, true,], [ true, false,],]
secondary = [ [ true, true,], [ false, false,],]

[beam2.strehl_model]
secondary = [ [ 1.0, 0.5,],]
exterior = [ [ 2.0, 1.0,],]

[beam2.H3.ctrl_model]
IM = [ [ 0.1, 0.2,], [ 0.3, 0.4,],]
I2A = [ [ 1.0, 2.0,], [ 3.0, 4.0,],]
I2M = [ [ 1.0, 2.0,], [ 3.0, 4.0,],]
I2M_LO = [ [ 1.0, 2.0,], [ 3.0, 4.0,],]
I2M_HO = [ [ 1.0, 2.0,], [ 3.0, 4.0,],]
M2C = [ [ 5.0, 6.0,], [ 7.0, 8.0,],]
M2C_LO = [ [ 5.0, 6.0,], [ 7.0, 8.0,],]
M2C_HO = [ [ 5.0, 6.0,], [ 7.0, 8.0,],]
I0 = [ [ 9.0,], [ 10.0,],]
N0 = [ [ 13.0,], [ 14.0,],]
norm_pupil = [ [ 17.0,], [ 18.0,],]
inner_pupil_filt = [ [ true,], [ false,],]
bad_pixel_mask = [ [ false,], [ true,],]
bias = [ [ 100.0,], [ 101.0,],]
dark = [ [ 0.1,], [ 0.1,],]

[beam2.H3.ctrl_model.camera_config]
fps = 0.033
gain = 1.5
