name = "Default Configuration"

#All units are in radians and microns
[geometry] 
hole_diameter   = 9e-3
beam_x          = [-15.6e-3,15.6e-3,0,0]
beam_y          = [-9e-3,-9e-3,0,18e-3]
pix = 24.0

#All units are in microns
[wave]
K1  = 2.05 
K2  = 2.35 
