name = "Default Configuration"

#All units are in radians and microns
[geometry] 
hole_diameter   = 9e-3
#beam_x          = [-9e-3,-9e-3,0,18e-3]
#beam_y          = [-15.6e-3,15.6e-3,0,0]
beam_x = [-0.00976843, -0.00820908,  0.0,  0.0179775 ]
beam_y = [-0.01513069,  0.01603032,  0.0, -0.00089963]
pix = 24.0

#All units are in microns
[wave]
K1  = 2.1 
K2  = 2.3 
